FROM node as build

RUN npm install -g @angular/cli@13.2.6
WORKDIR /app
RUN ls
ADD ./package.json /app/
RUN npm install --force
ADD ./ /app/
RUN ng build
EXPOSE $PORT

RUN useradd -u 2737 well
USER well
CMD ["node", "dist/cineweb/server/main.js"]

