FROM node as build

RUN npm install -g @angular/cli@13.2.6
WORKDIR /app
RUN ls
ADD ./package.json /app/
RUN npm install --force
ADD ./ /app/
RUN ng build
EXPOSE 80

CMD ["node", "dist/cineweb/server/main.js"]