version: "2.2"

services:
 cineweb-portal:
  container_name: cineweb-portal
  image: cineweb-portal
  environment:
  - PORT=5000
  ports:
  - 5000:5000
  build:
   context: .
   dockerfile: Dockerfile